### ISSUE TITLE
REFramework for Dragon's Dogma 2 launched with Steam Emulator

### ISSUE THREAD

**Issue by FCPerfectO** [hect0x7/hect0x7#2]
Hello hect0x7,

As far as I know, there was a version of "REFramework for EMPRESS RE4R (hect0x build)- no upscaler (full fps)".

Few days ago, it becomes possible to launch Dragon's Dogma 2 with Steam Emulator, but author of original REFramework don't want to add support for this type of the game. Can you please help us and make a version of REFramework for Steam emulated Dragon's Dogma 2?

Your old version for other game "REFramework for EMPRESS RE4R (hect0x build)- no upscaler (full fps)" starts working with emulated DD2, but after few seconds the game is closed with errors in REFramework log. It is obvious, because this old version doesn't support DD2, but it is trying to launch with DD2, so we now have a hope.

I hope you can help us with the solution.

[re2_framework_log.txt](https://github.com/user-attachments/files/16107749/re2_framework_log.txt)

[reframework_crash.dmp](https://github.com/user-attachments/files/16107804/reframework_crash.dmp)

Final beta build for DD2 - [DD2.zip](https://github.com/user-attachments/files/16108109/DD2.zip)

![REF with emu DD2](https://github.com/hect0x7/hect0x7/assets/30981401/4e125ca5-a30e-4c15-b969-3cca315b3b54)

**Comment by hect0x7** [comment]
Sorry to hear that. Since I'm actually not familiar with REFramework code and related games, I won't continue to work on things related to REFramework. Maybe other developers who know it better can help you, and I hope you succeed.
